# Generated by Django 2.1.5 on 2019-09-15 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('LG', 'LG')], max_length=20, verbose_name='Телефон')),
                ('phone_model', models.CharField(max_length=10, verbose_name='Модель Телефона')),
                ('image', models.ImageField(default='default.png', upload_to='phone_pics', verbose_name='Картинка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Имя')),
                ('metro', models.CharField(choices=[('Адмиралтейская', 'Адмиралтейская'), ('Новочеркасская', 'Новочеркасская'), ('Площадь Восстания', 'Площадь Восстания')], max_length=20, verbose_name='Станция Метро')),
                ('comments', models.TextField(verbose_name='Комментарии Пользователя')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Публикации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'информация',
                'verbose_name_plural': 'информация',
            },
        ),
    ]
