# Generated by Django 2.2.4 on 2019-08-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung')], max_length=20, verbose_name='телефон')),
                ('phone_model', models.CharField(max_length=10, verbose_name='модель телефона')),
                ('image', models.ImageField(default='default.png', upload_to='phone_pics', verbose_name='картинка')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='имя')),
                ('metro', models.CharField(choices=[('Адмиралтейская', 'Адмиралтейская')], max_length=20, verbose_name='станция метро')),
                ('comments', models.TextField(verbose_name='комментарии пользователя')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'информация',
                'verbose_name_plural': 'информация',
            },
        ),
    ]
