# Generated by Django 2.1.5 on 2019-09-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20190915_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии Пользователя'),
        ),
    ]
