# Generated by Django 2.2.4 on 2019-09-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phone', '0002_auto_20190902_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung')], max_length=20, verbose_name='телефон')),
                ('phone_model', models.CharField(max_length=10, verbose_name='модель телефона')),
                ('image', models.ImageField(default='default.png', upload_to='phone_pics', verbose_name='картинка')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='имя')),
                ('metro', models.CharField(choices=[('Адмиралтейская', 'Адмиралтейская')], max_length=20, verbose_name='станция метро')),
                ('comments', models.TextField(verbose_name='комментарии пользователя')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'информация',
                'verbose_name_plural': 'информация',
            },
        ),
        migrations.DeleteModel(
            name='PhoneInfo',
        ),
    ]
