# Generated by Django 2.1.5 on 2019-09-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_auto_20190916_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(help_text='Input your phone number in format 79XXXXXXXXX', max_length=11, verbose_name='Номер телефона'),
        ),
    ]
