# Generated by Django 2.2.4 on 2019-09-04 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_auto_20190904_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(default='+79062780534', max_length=15, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='comments',
            field=models.TextField(verbose_name='Комментарии Пользователя'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(default='default.png', upload_to='phone_pics', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='metro',
            field=models.CharField(choices=[('Адмиралтейская', 'Адмиралтейская'), ('Новочеркасская', 'Новочеркасская'), ('Площадь Восстания', 'Площадь Восстания')], max_length=20, verbose_name='Станция Метро'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('LG', 'LG')], max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_model',
            field=models.CharField(max_length=10, verbose_name='Модель Телефона'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Публикации'),
        ),
    ]
