# Generated by Django 2.1.5 on 2019-08-05 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=20)),
                ('drive', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('mileage', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('comments', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.png', upload_to='auto_pics')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
    ]
